// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzZ4fhtVZFsLbsTo3LRbZQSVChR1jeNM',
    appId: '1:699635307996:android:8c1f553abdda6f54d6ab19',
    messagingSenderId: '699635307996',
    projectId: 'ecommerceapp-83767',
    databaseURL: 'https://ecommerceapp-83767.firebaseio.com',
    storageBucket: 'ecommerceapp-83767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTVL8onnZPCzozb-Y-C9dEYQ8URZbIcHw',
    appId: '1:699635307996:ios:853aa5c38d625f24d6ab19',
    messagingSenderId: '699635307996',
    projectId: 'ecommerceapp-83767',
    databaseURL: 'https://ecommerceapp-83767.firebaseio.com',
    storageBucket: 'ecommerceapp-83767.appspot.com',
    androidClientId: '699635307996-rajptckfb2ujsvg54nif7pne2ta9d2mm.apps.googleusercontent.com',
    iosClientId: '699635307996-l7s0c5p80ikhsvmirk1g1pmpfng7l39q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAdminApp',
  );
}
